# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import blockchain_sync_pb2 as blockchain__sync__pb2


class BlockchainSyncServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncBlockchain = channel.unary_unary(
                '/blockchain.BlockchainSyncService/SyncBlockchain',
                request_serializer=blockchain__sync__pb2.SyncRequest.SerializeToString,
                response_deserializer=blockchain__sync__pb2.SyncResponse.FromString,
                )


class BlockchainSyncServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncBlockchain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockchainSyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncBlockchain': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncBlockchain,
                    request_deserializer=blockchain__sync__pb2.SyncRequest.FromString,
                    response_serializer=blockchain__sync__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blockchain.BlockchainSyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlockchainSyncService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncBlockchain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blockchain.BlockchainSyncService/SyncBlockchain',
            blockchain__sync__pb2.SyncRequest.SerializeToString,
            blockchain__sync__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
