# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_sync.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62lockchain_sync.proto\x12\nblockchain\"0\n\x0bSyncRequest\x12!\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x11.blockchain.Block\"1\n\x0cSyncResponse\x12!\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x11.blockchain.Block\"\x8c\x01\n\x05\x42lock\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x15\n\rprevious_hash\x18\x02 \x01(\t\x12-\n\x0ctransactions\x18\x03 \x03(\x0b\x32\x17.blockchain.Transaction\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x12\n\x05nonce\x18\x05 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_nonce\"@\n\x0bTransaction\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x32\\\n\x15\x42lockchainSyncService\x12\x43\n\x0eSyncBlockchain\x12\x17.blockchain.SyncRequest\x1a\x18.blockchain.SyncResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blockchain_sync_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYNCREQUEST._serialized_start=37
  _SYNCREQUEST._serialized_end=85
  _SYNCRESPONSE._serialized_start=87
  _SYNCRESPONSE._serialized_end=136
  _BLOCK._serialized_start=139
  _BLOCK._serialized_end=279
  _TRANSACTION._serialized_start=281
  _TRANSACTION._serialized_end=345
  _BLOCKCHAINSYNCSERVICE._serialized_start=347
  _BLOCKCHAINSYNCSERVICE._serialized_end=439
# @@protoc_insertion_point(module_scope)
