# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servicediscovery.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16servicediscovery.proto\"\x17\n\x04Peer\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x1d\n\x05Peers\x12\x14\n\x05peers\x18\x01 \x03(\x0b\x32\x05.Peer2F\n\tDiscovery\x12\x1b\n\x08Register\x12\x05.Peer\x1a\x06.Peers\"\x00\x12\x1c\n\tFindPeers\x12\x05.Peer\x1a\x06.Peers\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servicediscovery_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PEER._serialized_start=26
  _PEER._serialized_end=49
  _PEERS._serialized_start=51
  _PEERS._serialized_end=80
  _DISCOVERY._serialized_start=82
  _DISCOVERY._serialized_end=152
# @@protoc_insertion_point(module_scope)
